Repository solop-develop/adempiere-grpc-server, pull requests merged in 2022-12, with the labels that each got.

#156 fix: Callout set context values.
  src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
Labels: bug, (REC) Records, (WIN) Windows

#157 fix: Search with sql IN validation.
  src/main/java/org/spin/base/util/DictionaryUtil.java
Labels: bug, (REC) Records, (ULP) UI Lookups, (FRM) Form

#158 feat: Update experimental branch with 3.9.3 support branch.
  src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
  src/main/java/org/spin/pos/service/CashManagement.java
  src/main/proto/point_of_sales.proto
Labels: enhancement, (POS) Point Of Sales, (CIO) Code Improvement or Optimization, (FRM) Form

#159 feat: Update 3.9.3 with experimental
  src/main/java/org/spin/base/util/ContextManager.java
  src/main/java/org/spin/base/util/DictionaryUtil.java
  src/main/java/org/spin/base/util/RecordUtil.java
  src/main/java/org/spin/base/util/ReferenceUtil.java
  src/main/java/org/spin/base/util/ValueUtil.java
  src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java
  src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
  src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java
  src/main/java/org/spin/grpc/service/InOutServiceImplementation.java
  src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java
  src/main/java/org/spin/grpc/service/OrderServiceImplementation.java
  src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java
  src/main/java/org/spin/grpc/service/ProductServiceImplementation.java
  src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
  src/main/proto/base_data_type.proto
Labels: (CIO) Code Improvement or Optimization

#153 feat: Delete Attachment
  build-docker/Dockerfile.prod
  build-docker/docker-compose.yml
  build-docker/stack.yml
  resources/standalone.yml
  src/main/java/org/spin/base/util/ConvertUtil.java
  src/main/java/org/spin/base/util/Services.java
  src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java
  src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/base_data_type.proto
  src/main/proto/business.proto
  src/main/proto/file_management.proto
  src/main/proto/point_of_sales.proto
Labels: enhancement, (WIN) Windows

#160 fix: SQL Role restriction payment search.
  src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java
Labels: bug, (ULP) UI Lookups, (FRM) Form

#161 fix: Matcher results Java 8 compatibility.
  src/main/java/org/spin/base/util/RecordUtil.java
  src/main/java/org/spin/base/util/ReferenceUtil.java
Labels: bug, (TRL) Translation, (CIO) Code Improvement or Optimization

#163 feat: Exists attachment on record.
  src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java
  src/main/proto/file_management.proto
Labels: enhancement

#164 feat: Separate Dashboarding Service.
  src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java
  src/main/proto/base_data_type.proto
  src/main/proto/business.proto
  src/main/proto/dashboarding.proto
Labels: enhancement, dashboard, (CIO) Code Improvement or Optimization

#165 feat: Improve file management services.
  src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java
  src/main/proto/file_management.proto
Labels: enhancement, (WIN) Windows, (CIO) Code Improvement or Optimization

#166 Feature/#base update
  build.gradle
  src/main/java/org/spin/base/setup/SetupLoader.java
  src/main/java/org/spin/base/util/ContextManager.java
  src/main/java/org/spin/base/util/ConvertUtil.java
  src/main/java/org/spin/base/util/RecordUtil.java
  src/main/java/org/spin/base/util/ReferenceInfo.java
  src/main/java/org/spin/base/util/ReferenceUtil.java
  src/main/java/org/spin/base/util/ValueUtil.java
  src/main/java/org/spin/base/util/WorkflowUtil.java
  src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
  src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
  src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java
  src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java
  src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java
  src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
  src/main/java/org/spin/grpc/service/EnrollmentServiceImplementation.java
  src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java
  src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java
  src/main/java/org/spin/grpc/service/InOutServiceImplementation.java
  src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java
  src/main/java/org/spin/grpc/service/LogsServiceImplementation.java
  src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java
  src/main/java/org/spin/grpc/service/OrderServiceImplementation.java
  src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java
  src/main/java/org/spin/grpc/service/PayrollActionNoticeServiceImplementation.java
  src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
  src/main/java/org/spin/grpc/service/ProductServiceImplementation.java
  src/main/java/org/spin/grpc/service/TimeControlServiceImplementation.java
  src/main/java/org/spin/grpc/service/UpdateImplementation.java
  src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
  src/main/java/org/spin/grpc/service/WebStoreServiceImplementation.java
  src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java
Labels: (ULB) Update Library

#167 feat: Add time zone on container.
  README.md
  build-docker/Dockerfile.prod
  build-docker/docker-compose.yml
  build-docker/stack.yml
Labels: enhancement, (CI/CD) Continuous Integration/Continous Delivery

#169 feat: Exists record references
  src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
  src/main/proto/business.proto
Labels: enhancement, (REC) Records, (UX) User Experience

#168 feat: Payment Print/Export.
  build-docker/Dockerfile.prod
  build-docker/docker-compose.yml
  build-docker/stack.yml
  resources/standalone.yml
  src/main/java/org/spin/base/util/ReferenceUtil.java
  src/main/java/org/spin/base/util/Services.java
  src/main/java/org/spin/grpc/service/PaymentPrintExportServiceImplementation.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/payment_print_export.proto
Labels: enhancement, (FRM) Form

#172 feat: Add final balace on Payment List.
  src/main/java/org/spin/grpc/service/PaymentPrintExportServiceImplementation.java
  src/main/proto/payment_print_export.proto
Labels: enhancement, (FRM) Form
