Repository solop-develop/adempiere-grpc-server, pull requests merged in 2022-10, with the labels that each got.

#116 fix: Login with GardenAdmin user.
  src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
Labels: bug, (SE) Security

#118 feat: Add confirm Resource Assignment.
  src/main/java/org/spin/grpc/service/TimeControlServiceImplementation.java
  src/main/proto/time_control.proto
Labels: enhancement, (RPT) Reports

#126 fix: Field Search unparseable sql where clause.
  src/main/java/org/spin/base/util/DictionaryUtil.java
  src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java
  src/main/java/org/spin/grpc/service/InOutServiceImplementation.java
  src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java
  src/main/java/org/spin/grpc/service/OrderServiceImplementation.java
  src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java
  src/main/java/org/spin/grpc/service/ProductServiceImplementation.java
  src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
Labels: bug, (ULP) UI Lookups, (FRM) Form

#120 feat: Add resource to order line.
  src/main/java/org/spin/base/util/ConvertUtil.java
  src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
  src/main/java/org/spin/grpc/service/TimeControlServiceImplementation.java
  src/main/proto/point_of_sales.proto
  src/main/proto/time_control.proto
Labels: enhancement, (POS) Point Of Sales

#121 fix: Set Boolean value on context.
  src/main/java/org/spin/base/util/ContextManager.java
Labels: bug, (CIO) Code Improvement or Optimization

#122 fix: Duplicated error message.
  src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
  src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
  src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java
  src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java
  src/main/java/org/spin/grpc/service/DashboardingServiceImplementation.java
  src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
  src/main/java/org/spin/grpc/service/InOutServiceImplementation.java
  src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java
  src/main/java/org/spin/grpc/service/LogsServiceImplementation.java
  src/main/java/org/spin/grpc/service/OrderServiceImplementation.java
  src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java
  src/main/java/org/spin/grpc/service/PayrollActionNoticeServiceImplementation.java
  src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
  src/main/java/org/spin/grpc/service/ProductServiceImplementation.java
  src/main/java/org/spin/grpc/service/UpdateImplementation.java
  src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
  src/main/java/org/spin/grpc/service/WebStoreServiceImplementation.java
  src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java
Labels: bug, (CIO) Code Improvement or Optimization

#123 fix: Revert login with role org assignment.
  src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
Labels: bug, (SE) Security

#124 fix: Login with user organization access.
  src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
  src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java
Labels: bug, (SE) Security

#43 fix: Report View Traslated.
  src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
Labels: bug, (RPT) Reports, (TRL) Translation

#42 fix: Process/Report Parameters Translated.
  src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
Labels: bug, (RPT) Reports, (TRL) Translation

#130 fix: Set integer value as decimal value without presicion.
  src/main/java/org/spin/base/util/ConvertUtil.java
  src/main/java/org/spin/base/util/ValueUtil.java
Labels: bug, (REC) Records

#127 fix: List confirmed resource assigment.
  src/main/java/org/spin/grpc/service/TimeControlServiceImplementation.java
  src/main/proto/time_control.proto
Labels: enhancement, (FRM) Form

#129 feat: Add display column location address.
  src/main/java/org/spin/base/util/ReferenceUtil.java
Labels: enhancement, (REC) Records, (ULP) UI Lookups

#132 fix: Document statuses add initial status.
  src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java
Labels: bug, (WFL) Workflows

#131 feat: Support to login with role uuid and organization uuid into url parameter
  src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
Labels: enhancement, (SE) Security

#134 fix: Display column on location address inverse.
  src/main/java/org/spin/base/util/DictionaryUtil.java
  src/main/java/org/spin/base/util/ReferenceUtil.java
Labels: (REC) Records, (ULP) UI Lookups

#135 feat: Add support to display column on Product Set Attribute Instance.
  src/main/java/org/spin/base/util/ReferenceUtil.java
Labels: enhancement, (REC) Records

#136 feat: List Product Attribute Instances.
  src/main/java/org/spin/grpc/service/MaterialManagementServiceImplementation.java
  src/main/proto/material_management.proto
Labels: enhancement, (ULP) UI Lookups, (FRM) Form

#137 fix: Login with Role UUID nonexistent.
  src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
Labels: bug, (SE) Security

#138 fix: Null Pointer Exception Dependent Fields.
  src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
Labels: bug, (WIN) Windows

#139 fix: Dependencies fields on translation tab.
  src/main/java/org/spin/grpc/service/DictionaryServiceImplementation.java
Labels: bug, (WIN) Windows
