Repository solop-develop/adempiere-grpc-server, pull requests merged in 2023-03, with the labels that each got.

#227 fix: Run Smart Browser process with selection.
  src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
Labels: bug, (PRC) Processes, (RPT) Reports, (SB) Smart Browser

#228 fix: Document statuses/actions without isSOTrx column.
  src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java
Labels: bug, (REC) Records, (WFL) Workflows

#229 fix: Zoom reference window.
  src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
  src/main/proto/base_data_type.proto
Labels: bug, (REC) Records, (WIN) Windows

#230 feat: Add time record.
  build-docker/backend.env
  build-docker/development.Dockerfile
  build-docker/production-alpine.Dockerfile
  build-docker/production.Dockerfile
  resources/standalone.yaml
  src/main/java/org/spin/base/util/Services.java
  src/main/java/org/spin/grpc/service/TimeRecordServiceImplementation.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/time_record.proto
Labels: enhancement, (FRM) Form

#231 feat: List issues and projects.
  src/main/java/org/spin/grpc/service/TimeRecordServiceImplementation.java
  src/main/proto/time_record.proto
Labels: enhancement, (FRM) Form

#232 feat: JWT Backward Compatibility.
  src/main/java/org/spin/authentication/AuthorizationServerInterceptor.java
  src/main/java/org/spin/base/util/ContextManager.java
  src/main/java/org/spin/base/util/SessionManager.java
  src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
Labels: enhancement, (SE) Security, (CIO) Code Improvement or Optimization

#234 fix: Validate bearer token.
  src/main/java/org/spin/authentication/AuthorizationServerInterceptor.java
  src/main/java/org/spin/authentication/BearerToken.java
  src/main/java/org/spin/base/util/ContextManager.java
  src/main/java/org/spin/base/util/SessionManager.java
  src/main/java/org/spin/grpc/service/AccessServiceImplementation.java
Labels: bug, (SE) Security

#235 fix: Token without bearer token.
  src/main/java/org/spin/authentication/BearerToken.java
Labels: bug, (SE) Security

#237 feat: Support attachment with JWT.
  build.gradle
  src/main/java/org/spin/grpc/service/FileManagementServiceImplementation.java
Labels: (SE) Security, (ULB) Update Library, (WIN) Windows

#238 feat: Rename access to security
  build-docker/backend.env
  build-docker/development.Dockerfile
  build-docker/docker-compose.yaml
  build-docker/production-alpine.Dockerfile
  build-docker/production.Dockerfile
  resources/standalone.yaml
  src/main/java/org/spin/authentication/AuthorizationServerInterceptor.java
  src/main/java/org/spin/base/util/Services.java
  src/main/java/org/spin/grpc/service/SecurityServiceImplementation.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/security.proto
Labels: enhancement, (SE) Security, (CIO) Code Improvement or Optimization

#243 fix: Change pagination.
  src/main/java/org/spin/base/util/RecordUtil.java
  src/main/java/org/spin/grpc/service/BusinessDataServiceImplementation.java
  src/main/java/org/spin/grpc/service/BusinessPartnerServiceImplementation.java
  src/main/java/org/spin/grpc/service/CoreFunctionalityImplementation.java
  src/main/java/org/spin/grpc/service/GeneralLedgerServiceImplementation.java
  src/main/java/org/spin/grpc/service/InOutServiceImplementation.java
  src/main/java/org/spin/grpc/service/InvoiceServiceImplementation.java
  src/main/java/org/spin/grpc/service/LogsServiceImplementation.java
  src/main/java/org/spin/grpc/service/OrderServiceImplementation.java
  src/main/java/org/spin/grpc/service/PaymentPrintExportServiceImplementation.java
  src/main/java/org/spin/grpc/service/PaymentServiceImplementation.java
  src/main/java/org/spin/grpc/service/PayrollActionNoticeServiceImplementation.java
  src/main/java/org/spin/grpc/service/PointOfSalesServiceImplementation.java
  src/main/java/org/spin/grpc/service/ProductServiceImplementation.java
  src/main/java/org/spin/grpc/service/TimeControlServiceImplementation.java
  src/main/java/org/spin/grpc/service/UpdateImplementation.java
  src/main/java/org/spin/grpc/service/UserInterfaceServiceImplementation.java
  src/main/java/org/spin/grpc/service/WebStoreServiceImplementation.java
  src/main/java/org/spin/grpc/service/WorkflowServiceImplementation.java
Labels: bug, (REC) Records, (UX) User Experience

#245 feat: Express Shipment form.
  build-docker/backend.env
  build-docker/development.Dockerfile
  build-docker/production-alpine.Dockerfile
  build-docker/production.Dockerfile
  build-docker/stack.yml
  resources/standalone.yaml
  src/main/java/org/spin/base/util/Services.java
  src/main/java/org/spin/grpc/service/ExpressShipmentServiceImplementation.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/express_shipment.proto
Labels: enhancement, (FRM) Form

#247 Add compose file changes for image
  docker-compose/docker-compose.yml
Labels: (CI/CD) Continuous Integration/Continous Delivery

#249 Add a default private key NOTE: ¡¡¡¡ONLY FOR TEST!!!!
  .settings/org.eclipse.buildship.core.prefs
  docker/Dockerfile
Labels: (CI/CD) Continuous Integration/Continous Delivery

#248 feat: Express Shipment Services.
  src/main/java/org/spin/grpc/service/ExpressShipmentServiceImplementation.java
Labels: enhancement, (FRM) Form

#250 feat: CD docker image.
  .github/workflows/publish.yml
Labels: enhancement, (CI/CD) Continuous Integration/Continous Delivery

#252 Fix deploy token
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: (CI/CD) Continuous Integration/Continous Delivery

#253 Fixed error with docker env values
  docker/Dockerfile
Labels: (CI/CD) Continuous Integration/Continous Delivery
