Repository solop-develop/adempiere-grpc-server, pull requests merged in 2024-10, with the labels that each got.

#891 feat: Add `Is Jasper Report` flag.
  build.gradle
  resources/adempiere-grpc-server.pb
  src/main/proto/dictionary.proto
Labels: enhancement, (RPT) Reports

#892 fix: Correct `Is Jasper Report` with backend.
  src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java
Labels: bug, enhancement, (RPT) Reports

#894 feat: Add Filter to List Issues
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementServiceLogic.java
  src/main/proto/issue_management.proto
Labels: enhancement, (FRM) Form

#895 feat: Add search product only stock available.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/field/product/ProductInfoLogic.java
  src/main/proto/field.product.proto
Labels: enhancement, (FRM) Form

#896 fix: `Issues` form list with pagination.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementServiceLogic.java
  src/main/proto/issue_management.proto
Labels: (FRM) Form

#897 fix: Remove parallel stream on issues form.
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementServiceLogic.java
Labels: bug, (FRM) Form

#899 feat: Add `UUID` on entity builder.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/base/util/ConvertUtil.java
  src/main/java/org/spin/base/util/RecordUtil.java
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/proto/base_data_type.proto
Labels: (REC) Records, (WIN) Windows

#900 feat: Overwrite display type on reference to `Button` fields.
  build.gradle
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/base/db/QueryUtil.java
  src/main/java/org/spin/base/util/ReferenceInfo.java
  src/main/java/org/spin/base/util/ReferenceUtil.java
  src/main/java/org/spin/grpc/service/BusinessData.java
  src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java
  src/main/java/org/spin/grpc/service/dictionary/Dictionary.java
  src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java
  src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java
  src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementLogic.java
  src/main/proto/dictionary.proto
Labels: bug, (REC) Records, (SB) Smart Browser, (WIN) Windows, (ULP) UI Lookups, (UX) User Experience

#903 fix: `IsActive` restriction with default value.
  src/main/java/org/spin/base/db/WhereClauseUtil.java
Labels: bug, (ULP) UI Lookups, (UX) User Experience

#904 feat: Run Process with window selection.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/dictionary/util/WindowUtil.java
  src/main/java/org/spin/grpc/service/BusinessData.java
  src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java
  src/main/proto/business.proto
Labels: enhancement, (PRC) Processes, (WIN) Windows

#908 feat: Get `PriceList` definition.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionality.java
  src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionalityConvert.java
  src/main/proto/core_functionality.proto
Labels: bug, (ULP) UI Lookups

#911 feat: Update docker images to `11.0.24_8`.
  README.es.md
  README.md
  docker/alpine.Dockerfile
  docker/focal.Dockerfile
  docker/start.sh
Labels: enhancement, (ULP) UI Lookups

#912 feat: Update GH Actions.
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  docker/grpc_proxy.Dockerfile
Labels: enhancement, (ULP) UI Lookups

#913 feat: Add end-point to window report.
  resources/adempiere-grpc-server.pb
  src/main/proto/report_management.proto
Labels: (RPT) Reports, (CIO) Code Improvement or Optimization

#914 feat: Add get currency service.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionality.java
  src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionalityConvert.java
  src/main/proto/core_functionality.proto
Labels: enhancement, (ULP) UI Lookups

#915 fix: Improves performance in the query count.
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, (REC) Records, (WIN) Windows

#917 feat: Add `gradlew`.
  gradlew
  gradlew.bat
Labels: enhancement, (CI/CD) Continuous Integration/Continous Delivery, (ULB) Update Library

#922 fix: DB Parameter with display type.
  build.gradle
  src/main/java/org/spin/base/db/WhereClauseUtil.java
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, (REC) Records, (WIN) Windows
