Repository solop-develop/adempiere-grpc-server, pull requests merged in 2024-07, with the labels that each got.

#806 feat: Table Name on field search display type.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/base/db/QueryUtil.java
  src/main/java/org/spin/grpc/service/dictionary/DictionaryServiceLogic.java
  src/main/proto/dictionary.proto
Labels: enhancement, (ULP) UI Lookups

#807 feat: Sort Tabs filter column name to list.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java
  src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
  src/main/proto/user_interface.proto
Labels: enhancement, (REC) Records, (WIN) Windows

#809 feat: Update descriptor with lookups.
  resources/adempiere-grpc-server.pb
Labels: enhancement, (ULP) UI Lookups

#810 fix: Save new with zero value.
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, enhancement, (REC) Records, (WIN) Windows

#811 fix: Callout cast string to date.
  src/main/java/org/spin/dictionary/util/WindowUtil.java
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, (WIN) Windows, (ULP) UI Lookups

#813 fix: Edit zero value on record.
  src/main/java/org/compiere/model/POAdapter.java
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java
Labels: bug, (REC) Records, (WIN) Windows

#814 feat: Add `Dictionary Code` on client info.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/Security.java
  src/main/proto/security.proto
Labels: enhancement

#815 Feature/get dictionary with UUID
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/Security.java
  src/main/java/org/spin/grpc/service/dictionary/Dictionary.java
  src/main/proto/dictionary.proto
Labels: enhancement, (PRC) Processes, (RPT) Reports, (SB) Smart Browser, (WIN) Windows, (FRM) Form

#816 fix: Payment Allocation form, with 0 organizaiton.
  src/main/java/org/spin/grpc/service/form/PaymentAllocation.java
Labels: bug, (FRM) Form

#817 SQL Error in Order Field (Payment)
  src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoLogic.java
  src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoService.java
  src/main/java/org/spin/grpc/service/field/order/OrderInfoLogic.java
  src/main/java/org/spin/grpc/service/field/payment/PaymentInfoLogic.java
Labels: bug, (ULP) UI Lookups

#818 feat: Add `UUID` field on `Workflow` services.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/base/util/WorkflowUtil.java
  src/main/proto/workflow.proto
Labels: enhancement, (WFL) Workflows

#819 fix: `Product` info field with role, org, and record access.
  src/main/java/org/spin/base/db/WhereClauseUtil.java
  src/main/java/org/spin/grpc/service/field/product/ProductInfoLogic.java
Labels: bug, (SE) Security, (ULP) UI Lookups, (FRM) Form

#820 fix: Change report output.
  src/main/java/org/spin/base/db/WhereClauseUtil.java
  src/main/java/org/spin/dictionary/util/ReportUtil.java
  src/main/java/org/spin/grpc/service/ReportManagement.java
Labels: bug, (RPT) Reports

#821 perf: Remove unused and dupicated definitions.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionality.java
  src/main/proto/core_functionality.proto
  src/main/proto/material_management.proto
  src/main/proto/security.proto
Labels: enhancement, (CIO) Code Improvement or Optimization

#822 fix: POS List Bank Accounts with mandatory Bank identifier.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/proto/in_out.proto
  src/main/proto/payment.proto
  src/main/proto/point_of_sales.proto
Labels: bug, (POS) Point Of Sales, (CIO) Code Improvement or Optimization, (FRM) Form

#823 fix: List Products with mandatory Order identifier.
  resources/adempiere-grpc-server.pb
  src/main/proto/express_receipt.proto
  src/main/proto/express_shipment.proto
Labels: bug, (CIO) Code Improvement or Optimization, (FRM) Form

#824 fix: List `IsActive` records on search field.
  src/main/java/org/spin/grpc/service/InOutInfo.java
  src/main/java/org/spin/grpc/service/field/business_partner/BusinessPartnerLogic.java
  src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoLogic.java
  src/main/java/org/spin/grpc/service/field/order/OrderInfoLogic.java
  src/main/java/org/spin/grpc/service/field/payment/PaymentInfoLogic.java
  src/main/java/org/spin/grpc/service/field/product/ProductInfoLogic.java
  src/main/java/org/spin/grpc/service/ui/UserInterfaceLogic.java
Labels: bug, (REC) Records, (SE) Security, (ULP) UI Lookups

#825 feat: Add support Send Notifications.
  docker/envoy_template.yaml
  resources/adempiere-grpc-server.pb
  resources/envoy.yaml
  src/main/java/org/spin/grpc/service/SendNotifications.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/send_notifications.proto
Labels: enhancement, (RPT) Reports, (UX) User Experience

#826 Fix: SQL Postgres 15
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/SendNotifications.java
  src/main/proto/send_notifications.proto
Labels: bug

#827 Feat: Support Send Notification
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/SendNotifications.java
  src/main/proto/send_notifications.proto
Labels: enhancement, (RPT) Reports, (UX) User Experience

#828 fix: Export menu tree for all nodes.
  build.gradle
Labels: bug, (MEN) Menues, (SE) Security

#830 feat: Add `S3 Connector` 1.0.2 version.
  build.gradle
Labels: enhancement, (ULB) Update Library, (ADC) ADempiere Core

#831 feat: Update `adempiere-grpc-utils` to 1.4.6 version.
  build.gradle
Labels: (ULB) Update Library, (CIO) Code Improvement or Optimization

#832 Remove Body Mandatory
  src/main/java/org/spin/grpc/service/SendNotifications.java
Labels: (RPT) Reports
