Repository solop-develop/adempiere-grpc-server, pull requests merged in 2024-04, with the labels that each got.

#732 feat: Change menu endpoint.
  build.gradle
  src/main/java/org/spin/grpc/service/Security.java
  src/main/proto/security.proto
Labels: enhancement, (MEN) Menues, (CIO) Code Improvement or Optimization

#733 feat: Add flag to filter only active records.
  src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java
  src/main/java/org/spin/grpc/service/GeneralLedger.java
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/form/PaymentAllocation.java
  src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchServiceLogic.java
  src/main/java/org/spin/grpc/service/form/match_po_receipt_invoice/MatchPOReceiptInvoice.java
  src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillableServiceLogic.java
  src/main/proto/bank_statement_match.proto
  src/main/proto/base_data_type.proto
  src/main/proto/general_ledger.proto
  src/main/proto/import_file_loader.proto
  src/main/proto/match_po_receipt_invoice.proto
  src/main/proto/payment_allocation.proto
  src/main/proto/payment_print_export.proto
  src/main/proto/payroll_action_notice.proto
  src/main/proto/product.proto
  src/main/proto/trial_balance_drillable.proto
Labels: (ULP) UI Lookups, (FRM) Form

#734 fix: Add table name on tab structure.
  src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
  src/main/proto/dictionary.proto
Labels: bug, (WIN) Windows

#735 fix: Menus without root element.
  src/main/java/org/spin/grpc/service/Security.java
Labels: bug

#736 feat: Enable all services by default.
  README.es.md
  README.md
  docker-compose/.env
  docker-compose/docker-compose.yml
  docker/alpine.Dockerfile
  docker/env.yaml
  docker/focal.Dockerfile
  docker/start.sh
  resources/standalone.yaml
  src/main/java/org/spin/base/setup/Server.java
  src/main/java/org/spin/base/util/Services.java
  src/main/java/org/spin/server/AllInOneServices.java
Labels: enhancement, (CIO) Code Improvement or Optimization

#737 feat: Set envoy proxy tiemout.
  docker/envoy_template.yaml
  resources/envoy.yaml
Labels: (CIO) Code Improvement or Optimization

#738 feat: Improve peformance with `parallelStream`.
  src/main/java/org/spin/base/db/WhereClauseUtil.java
  src/main/java/org/spin/base/util/ContextManager.java
  src/main/java/org/spin/base/util/ConvertUtil.java
  src/main/java/org/spin/base/util/RecordUtil.java
  src/main/java/org/spin/base/util/ReferenceInfo.java
  src/main/java/org/spin/dictionary/util/ReportUtil.java
  src/main/java/org/spin/form/import_file_loader/ImportFileLoaderConvertUtil.java
  src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java
  src/main/java/org/spin/grpc/logic/RecordManagementServiceLogic.java
  src/main/java/org/spin/grpc/service/BusinessData.java
  src/main/java/org/spin/grpc/service/GeneralLedger.java
  src/main/java/org/spin/grpc/service/ReportManagement.java
  src/main/java/org/spin/grpc/service/Security.java
  src/main/java/org/spin/grpc/service/UserCustomization.java
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/WebStore.java
  src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionality.java
  src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java
  src/main/java/org/spin/grpc/service/dictionary/Dictionary.java
  src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java
  src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java
  src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
  src/main/java/org/spin/grpc/service/field/location_address/LocationAddressLogic.java
  src/main/java/org/spin/grpc/service/form/ExpressMovement.java
  src/main/java/org/spin/grpc/service/form/ExpressReceipt.java
  src/main/java/org/spin/grpc/service/form/ExpressShipment.java
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagement.java
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementServiceLogic.java
  src/main/java/org/spin/grpc/service/form/payroll_action_notice/PayrollActionNotice.java
  src/main/java/org/spin/log/LogsConvertUtil.java
  src/main/java/org/spin/pos/service/bank/BankManagement.java
Labels: (CIO) Code Improvement or Optimization

#739 fix: PG 15 with `ColumnSQL`.
  src/main/java/org/spin/base/db/QueryUtil.java
Labels: bug, (WIN) Windows

#740 fix: Change `ValidFileName` to `FileName`.
  src/main/java/org/spin/grpc/service/Security.java
  src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionalityConvert.java
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementConvertUtil.java
Labels: bug, (UX) User Experience

#742 fix: Dashboard content translation.
  src/main/java/org/spin/grpc/service/Dashboarding.java
Labels: bug, dashboard, (TRL) Translation

#743 feat: Add `action_uuid` on Menu structure.
  src/main/java/org/spin/grpc/service/Security.java
  src/main/proto/security.proto
Labels: (MEN) Menues, (CIO) Code Improvement or Optimization

#745 fix: Issue feed sorted by date.
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagement.java
Labels: bug, (FRM) Form

#747 fix: Filter pending documents.
  src/main/java/org/spin/base/db/WhereClauseUtil.java
  src/main/java/org/spin/grpc/logic/RecordManagementServiceLogic.java
  src/main/java/org/spin/grpc/service/Dashboarding.java
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/proto/dashboarding.proto
Labels: bug, dashboard, (WIN) Windows

#746 fix: `java.util.NoSuchElementException: No value present`.
  src/main/java/org/spin/base/util/ConvertUtil.java
  src/main/java/org/spin/dictionary/util/WindowUtil.java
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/grpc/service/UserCustomization.java
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/Workflow.java
  src/main/java/org/spin/pos/service/order/OrderManagement.java
  src/main/java/org/spin/pos/service/order/ReturnSalesOrder.java
  src/main/java/org/spin/pos/util/POSConvertUtil.java
Labels: bug, (UX) User Experience

#748 fix: Edit record without own key column`AD_ClientInfo=AD_Client_ID`.
  src/main/java/org/spin/base/util/RecordUtil.java
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, (WIN) Windows

#749 fix: Update entity with `parallelStream`.
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, (REC) Records, (SB) Smart Browser

#750 fix: Inexistent column as key filer.
  src/main/java/org/spin/base/db/WhereClauseUtil.java
Labels: bug, (REC) Records

#754 feat: Invoice field.
  docker/envoy_template.yaml
  src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfo.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/invoice.proto
Labels: enhancement, (ULP) UI Lookups

#753 fix: Filter manager without list.
  src/main/java/org/spin/base/db/WhereClauseUtil.java
  src/main/java/org/spin/base/query/Filter.java
  src/main/java/org/spin/base/query/FilterManager.java
Labels: bug, (REC) Records

#752 fix: Accouting combination field.
  src/main/java/org/spin/grpc/service/GeneralLedger.java
  src/main/proto/general_ledger.proto
Labels: bug, (ULP) UI Lookups

#755 feat: Invoice fied `GetInvoice` and `ListInvoicePaySchedules` services.
  src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfo.java
  src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoConvert.java
  src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoLogic.java
  src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoService.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/invoice.proto
Labels: enhancement, (ULP) UI Lookups

#757 feat: Change container to parent on dependent field.
  src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java
  src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java
  src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java
  src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
  src/main/proto/dictionary.proto
Labels: enhancement, (PRC) Processes, (RPT) Reports, (SB) Smart Browser, (WIN) Windows, (CIO) Code Improvement or Optimization

#756 fix: Edit browse entity on field read only.
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, (REC) Records, (SB) Smart Browser

#758 feat: Update `adempiere-kafka-connector` and `adempiere-grpc-utils` libraries
  build.gradle
  src/main/java/org/spin/log/LogsConvertUtil.java
Labels: (ULB) Update Library, (CIO) Code Improvement or Optimization
