Repository solop-develop/adempiere-grpc-server, pull requests merged in 2024-08, with the labels that each got.

#834 fix: Report display value fields as `Date`, `Numeric` and `YesNo`.
  build.gradle
Labels: enhancement, (RPT) Reports, (ULB) Update Library, (ULP) UI Lookups, (ADC) ADempiere Core

#835 feat: Add client uuid on record as `AD_Client_ID_UUID`.
  src/main/java/org/spin/base/util/RecordUtil.java
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: enhancement, (REC) Records, Attachment

#837 fix: Remove ASP manage.
  src/main/java/org/spin/base/db/OrderByUtil.java
  src/main/java/org/spin/base/db/QueryUtil.java
  src/main/java/org/spin/base/db/WhereClauseUtil.java
  src/main/java/org/spin/base/util/ReferenceInfo.java
  src/main/java/org/spin/base/util/WorkflowUtil.java
  src/main/java/org/spin/dictionary/util/ReportUtil.java
  src/main/java/org/spin/dictionary/util/WindowUtil.java
  src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java
  src/main/java/org/spin/grpc/service/ReportManagement.java
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java
  src/main/java/org/spin/grpc/service/dictionary/Dictionary.java
  src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java
  src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementConvert.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementLogic.java
  src/main/java/org/spin/grpc/service/ui/BrowserLogic.java
Labels: (REC) Records, (RPT) Reports, (SB) Smart Browser, (WIN) Windows, (CIO) Code Improvement or Optimization

#836 fix: Login with updated `io.jsonwebtoken:jjwt` lib to `0.12.6`.
  build.gradle
Labels: bug, (SE) Security, (ULB) Update Library

#838 fix: Smart Browse `Order By` lookups by display columns.
  src/main/java/org/spin/base/db/OrderByUtil.java
  src/main/java/org/spin/base/util/LookupUtil.java
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, (REC) Records, (SB) Smart Browser, (CIO) Code Improvement or Optimization

#839 fix: Downgrade `adempiere-kafka-connector` to 1.3.0 version.
  build.gradle
Labels: bug, (ULB) Update Library

#840 fix: Notice and notificactions changes.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/NoticeManagement.java
  src/main/java/org/spin/grpc/service/SendNotifications.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/notice_management.proto
  src/main/proto/send_notifications.proto
Labels: (CIO) Code Improvement or Optimization, (UX) User Experience

#841 feat: Update gradle actions.
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  build.gradle
Labels: (ULB) Update Library

#842 fix: SQL process associated with asp.
  src/main/java/org/spin/dictionary/util/WindowUtil.java
  src/main/java/org/spin/grpc/service/ui/UserInterfaceLogic.java
Labels: (PRC) Processes, (RPT) Reports, (SE) Security, (WIN) Windows

#843 Fix: Validate Organization ID
  src/main/java/org/spin/grpc/service/GeneralLedger.java
Labels: bug, (ULP) UI Lookups

#845 fix: Change endpoints to send-notifications.
  resources/adempiere-grpc-server.pb
  src/main/proto/send_notifications.proto
Labels: (RPT) Reports, (CIO) Code Improvement or Optimization, (UX) User Experience

#846 feat: Improve menu load.
  src/main/java/org/spin/grpc/service/Security.java
Labels: (MEN) Menues, (SE) Security

#847 feat: Improve logs message.
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/ui/UserInterfaceLogic.java
Labels: enhancement, (CIO) Code Improvement or Optimization

#849 fix: Mandatory file name to start Setup loader.
  src/main/java/org/spin/base/setup/SetupLoader.java
Labels: (CIO) Code Improvement or Optimization

#850 fix: Dependent fields.
  src/main/java/org/spin/base/util/ContextManager.java
  src/main/java/org/spin/base/util/LookupUtil.java
  src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java
  src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java
  src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
Labels: (PRC) Processes, (RPT) Reports, (SB) Smart Browser, (WIN) Windows, (CIO) Code Improvement or Optimization

#851 feat: Update kafka connector 1.3.6
  build.gradle
  src/main/java/org/spin/base/util/ContextManager.java
Labels: enhancement, (ULB) Update Library

#853 fix: Table reference without table validation.
  src/main/java/org/spin/base/db/QueryUtil.java
  src/main/java/org/spin/base/util/ReferenceUtil.java
Labels: bug, (ULP) UI Lookups

#854 feat: Implement lookup display column key method.
  src/main/java/org/spin/grpc/service/form/match_po_receipt_invoice/MatchPOReceiptInvoice.java
  src/main/java/org/spin/grpc/service/form/payroll_action_notice/PayrollActionNotice.java
Labels: bug, (ULP) UI Lookups

#858 fix: Load child records.
  src/main/java/org/spin/base/db/WhereClauseUtil.java
  src/main/java/org/spin/dictionary/util/WindowUtil.java
Labels: bug, (REC) Records, (WIN) Windows

#856 Fix Get File from S3
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java
  src/main/proto/import_file_loader.proto
Labels: enhancement, (FRM) Form, Attachment

#860 fix: Callout with `@script` as MRule.
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, (WIN) Windows

#859 Establishing Organization ID from the Context
  src/main/java/org/spin/grpc/service/GeneralLedger.java
Labels: bug, (FRM) Form

#861 feat: Add report flag `is_process_before_launch`.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java
  src/main/proto/dictionary.proto
Labels: enhancement, (RPT) Reports

#862 feat: Add zoom window by table name.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/logic/RecordManagementServiceLogic.java
  src/main/java/org/spin/grpc/service/RecordManagement.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementConvert.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementLogic.java
  src/main/proto/record_management.proto
Labels: enhancement, (REC) Records, (WIN) Windows

#864 feat: Increase default JVM Arguments on gradle.
  gradle.properties
Labels: (CI/CD) Continuous Integration/Continous Delivery, (CIO) Code Improvement or Optimization

#865 Fixed: Process `Import File Loader` form with file name
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java
  src/main/proto/import_file_loader.proto
Labels: enhancement, (FRM) Form, Attachment

#866 feat: Reestructure UI to Field Management services.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/form/import_file_loader/ImportFileLoaderServiceLogic.java
  src/main/java/org/spin/grpc/service/GeneralLedger.java
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementConvert.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementLogic.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementService.java
  src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoLogic.java
  src/main/java/org/spin/grpc/service/field/order/OrderInfoLogic.java
  src/main/java/org/spin/grpc/service/field/payment/PaymentInfoLogic.java
  src/main/java/org/spin/grpc/service/field/product/ProductInfoLogic.java
  src/main/java/org/spin/grpc/service/form/PaymentAllocation.java
  src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchServiceLogic.java
  src/main/java/org/spin/grpc/service/form/match_po_receipt_invoice/MatchPOReceiptInvoice.java
  src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillableServiceLogic.java
  src/main/java/org/spin/grpc/service/ui/UserInterfaceLogic.java
  src/main/proto/field_management.proto
  src/main/proto/user_interface.proto
Labels: (CI/CD) Continuous Integration/Continous Delivery, (UIX) User Experience, (ULP) UI Lookups, (CIO) Code Improvement or Optimization

#867 fix: Tab and Field translation.
  src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
Labels: bug, (TRL) Translation, (WIN) Windows

#868 feat: List Zoom Windows by table id.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/logic/RecordManagementServiceLogic.java
  src/main/proto/record_management.proto
Labels: (REC) Records, (WIN) Windows, (UX) User Experience

#869 fix: Translate list values on records.
  src/main/java/org/spin/base/db/QueryUtil.java
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java
  src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java
  src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java
  src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
Labels: bug, (REC) Records, (TRL) Translation

#870 feat: Add get Preference.
  docker/envoy_template.yaml
  resources/envoy.yaml
  src/main/java/org/spin/grpc/service/PreferenceManagement.java
  src/main/java/org/spin/server/AllInOneServices.java
Labels: enhancement, (UX) User Experience

#871 feat: Change search fields end-point.
  docker/envoy_template.yaml
  docker/grpc_proxy.Dockerfile
  resources/adempiere-grpc-server.pb
  resources/envoy.yaml
  src/main/java/org/spin/grpc/service/field/in_out/InOutInfoService.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/field.business_partner.proto
  src/main/proto/field.in_out.proto
  src/main/proto/field.invoice.proto
  src/main/proto/field.order.proto
  src/main/proto/field.payment.proto
  src/main/proto/field.product.proto
  src/main/proto/field.proto
Labels: (ULP) UI Lookups, (CIO) Code Improvement or Optimization

#872 fix: List tables `Import File Loader` form.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/SendNotifications.java
  src/main/java/org/spin/grpc/service/form/import_file_loader/ImportFileLoader.java
  src/main/java/org/spin/grpc/service/form/import_file_loader/ImportFileLoaderConvertUtil.java
  src/main/java/org/spin/grpc/service/form/import_file_loader/ImportFileLoaderServiceLogic.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/import_file_loader.proto
Labels: bug, (FRM) Form

#873 Error number of records in the Document Pending
  src/main/java/org/spin/grpc/service/Dashboarding.java
Labels: bug, dashboard

#874 fix: `Payment` search field load records.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/field/payment/PaymentInfoConvert.java
  src/main/java/org/spin/grpc/service/field/payment/PaymentInfoLogic.java
  src/main/java/org/spin/grpc/service/field/payment/PaymentInfoService.java
  src/main/proto/field.payment.proto
Labels: bug, (ULP) UI Lookups, (FRM) Form

#875 fix: List `Print Formats` null pointer exception with table.
  src/main/java/org/spin/grpc/service/ReportManagement.java
Labels: bug, (RPT) Reports
