Repository solop-develop/adempiere-grpc-server, pull requests merged in 2024-09, with the labels that each got.

#877 Bugfix/role access with string UUID
  build.gradle
Labels: bug, (SE) Security

#879 fix: Kafka connector version
  build.gradle
Labels: bug, (ULB) Update Library

#883 fix: Remove redundant libs
  build.gradle
Labels: enhancement, (ULP) UI Lookups

#886 fix: SB process all records on server.
  src/main/java/org/spin/grpc/service/BusinessData.java
Labels: bug, (PRC) Processes, (REC) Records, (SB) Smart Browser

#880 Error in DefaultValue with Special Values
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementLogic.java
Labels: bug, (ULP) UI Lookups

#889 feat: Add window uuid to zoom.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementConvert.java
  src/main/proto/field.proto
Labels: (RPT) Reports, (ULP) UI Lookups

#890 fix: `Payment Rule` field with Button as List display type.
  src/main/java/org/spin/base/util/ReferenceInfo.java
Labels: bug, (ULP) UI Lookups, (FRM) Form
