Repository solop-develop/adempiere-grpc-server, pull requests merged in 2024-05, with the labels that each got.

#761 feat: Update `kafka-connector` to 1.2.0.
  build.gradle
Labels: bug, (ULB) Update Library

#762 feat: Update `adempiere-kafka-connector` to `1.2.1`.
  build.gradle
Labels: enhancement, (CIO) Code Improvement or Optimization, (FRM) Form

#763 feat: `Envoy Proxy` add logs and update to `1.29.4`.
  docker/envoy_template.yaml
  docker/grpc_proxy.Dockerfile
  resources/envoy.yaml
Labels: enhancement, (CIO) Code Improvement or Optimization

#766 fix: Key `Name` on filters.
  src/main/java/org/spin/base/query/Filter.java
Labels: bug, (REC) Records, (SB) Smart Browser, (WIN) Windows

#767 fix: `Location` field return coordinantes.
  src/main/java/org/spin/grpc/service/field/location_address/LocationAddressConvertUtil.java
  src/main/java/org/spin/grpc/service/field/location_address/LocationAddressLogic.java
Labels: bug, (ULP) UI Lookups

#768 feat: Additional context as tempory workaround.
  src/main/java/org/spin/base/interim/ContextTemporaryWorkaround.java
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/ui/CalloutLogic.java
Labels: (WIN) Windows, (CIO) Code Improvement or Optimization

#769 feat: Get Dictionary Access.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/Security.java
  src/main/proto/product.proto
  src/main/proto/security.proto
Labels: enhancement, (SE) Security, (CIO) Code Improvement or Optimization

#776 fix: Express forms revert parallel strem with context.
  src/main/java/org/spin/grpc/service/form/ExpressMovement.java
  src/main/java/org/spin/grpc/service/form/ExpressReceipt.java
  src/main/java/org/spin/grpc/service/form/ExpressShipment.java
Labels: bug, (FRM) Form

#774 feat: Add `Display Value` and `Product Classification` on product field.
  src/main/java/org/spin/grpc/service/field/product/ProductInfoConvert.java
  src/main/java/org/spin/grpc/service/field/product/ProductInfoLogic.java
  src/main/proto/product.proto
Labels: enhancement, (ULP) UI Lookups, (FRM) Form

#775 feat: Add `Display Value` on invoice field.
  src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoConvert.java
  src/main/proto/invoice.proto
Labels: enhancement, (ULP) UI Lookups

#773 fix: Window `Browser` associated as button or process.
  build.gradle
  docker/grpc_proxy.Dockerfile
Labels: bug, (PRC) Processes, (SB) Smart Browser, (WIN) Windows

#771 Fix List Invoices Info Query
  src/main/java/org/spin/base/db/WhereClauseUtil.java
  src/main/java/org/spin/grpc/service/field/invoice/InvoiceInfoLogic.java
Labels: bug, (ULP) UI Lookups

#778 fix: `Invoice Field` end-points.
  src/main/proto/invoice.proto
Labels: bug, (ULP) UI Lookups

#780 fix: Add context (emulating callouts) as unknow columns.
  src/main/java/org/spin/base/interim/ContextTemporaryWorkaround.java
  src/main/java/org/spin/base/util/ConvertUtil.java
  src/main/java/org/spin/base/util/RecordUtil.java
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, (REC) Records, (WIN) Windows

#777 Feat: `Order` field detail info.
  docker/envoy_template.yaml
  resources/adempiere-grpc-server.pb
  resources/envoy.yaml
  src/main/java/org/spin/grpc/service/OrderInfo.java
  src/main/java/org/spin/grpc/service/field/order/OrderInfoConvert.java
  src/main/java/org/spin/grpc/service/field/order/OrderInfoLogic.java
  src/main/java/org/spin/grpc/service/field/order/OrderInfoService.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/order.proto
  src/main/proto/order_info.proto
Labels: enhancement, (ULP) UI Lookups, (UX) User Experience

#779 fix: Report provider to jasper.
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/java/org/spin/server/ServerReportProvider.java
Labels: bug, (RPT) Reports

#784 fix: Context with `parallelStream`.
  src/main/java/org/spin/base/interim/ContextTemporaryWorkaround.java
  src/main/java/org/spin/base/util/ContextManager.java
  src/main/java/org/spin/grpc/service/Security.java
  src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionality.java
Labels: bug, (SE) Security

#785 feat: Field zoom to window.
  docker/envoy_template.yaml
  resources/adempiere-grpc-server.pb
  resources/envoy.yaml
  src/main/java/org/spin/base/util/ContextManager.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementConvert.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementLogic.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementService.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/field_management.proto
Labels: bug, (WIN) Windows, (ULP) UI Lookups

#786 fix: Index name with all values.
  build.gradle
Labels: bug, (MEN) Menues, (SE) Security

#787 feat: Zoom to parent tab.
  build.gradle
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/dictionary/DictionaryConvertUtil.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementConvert.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementLogic.java
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementService.java
  src/main/proto/dictionary.proto
  src/main/proto/field_management.proto
Labels: enhancement, (ULP) UI Lookups

#788 Fix: Validate values in Null
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, (REC) Records, (SB) Smart Browser, (WIN) Windows
