Repository solop-develop/adempiere-grpc-server, pull requests merged in 2025-03, with the labels that each got.

#1048 feat: Process `Out Bound Order` form.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java
  src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderService.java
  src/main/proto/form.out_bound_order.proto
Labels: enhancement, (FRM) Form

#1049 fix: Remove potential `NPE`.
  src/main/java/org/spin/grpc/service/field/field_management/FieldManagementLogic.java
Labels: bug, (ULP) UI Lookups

#1051 fix: Overwrite dynamic validation.
  src/main/java/org/spin/base/util/ReferenceInfo.java
Labels: bug, (ULP) UI Lookups

#1052 fix: Out Bound Oder form, list document types.
  src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java
Labels: bug, (FRM) Form

#1053 fix: Out Bound Order Empty row on selection without lines.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderConvertUtil.java
  src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java
  src/main/proto/form.out_bound_order.proto
Labels: bug, (FRM) Form

#1054 Bugfix/out bound order list warehouse inactive
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java
  src/main/proto/form.out_bound_order.proto
Labels: bug, (SE) Security, (FRM) Form

#1055 fix: Out Bound Order undefined movement type.
  src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java
Labels: bug, (FRM) Form

#1056 feat: Out Bound Order form create Freight Order.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java
  src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderService.java
  src/main/proto/form.out_bound_order.proto
Labels: enhancement, (FRM) Form

#1057 fix: Generate `Order Freight` from `Out Bound Order` form.
  src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java
Labels: bug, (FRM) Form

#1058 feat: Display Definition Info as Field.
  gradle.properties
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionConvertUtil.java
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java
  src/main/proto/display_definition.proto
Labels: enhancement, (ULP) UI Lookups

#1059 feat: Display Definition Field with `IsSelectionColumn`.
  gradle.properties
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionConvertUtil.java
  src/main/proto/display_definition.proto
Labels: enhancement, (ULB) Update Library

#1064 fix: Discount amount/percent to all document.
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/pos/util/OrderConverUtil.java
Labels: bug, (POS) Point Of Sales

#1060 feat: Display Definition to create business partner.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinition.java
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionConvertUtil.java
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java
  src/main/proto/display_definition.proto
Labels: enhancement, (ULP) UI Lookups, (FRM) Form

#1066 fix: Report error message when is not error.
  src/main/java/org/spin/grpc/service/ReportManagement.java
Labels: bug, (RPT) Reports

#1065 fix: Display Definition change BP service.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionConvertUtil.java
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java
  src/main/proto/display_definition.proto
Labels: bug, (UIX) User Experience, (ULP) UI Lookups

#1067 fix: Dynamic Validation on window not working.
  src/main/java/org/spin/base/util/ReferenceInfo.java
Labels: bug, (SE) Security, (WIN) Windows, (ULP) UI Lookups

#1068 feat: Load fields on display definition as isInserRecord.
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java
Labels: bug, (WIN) Windows, (ULP) UI Lookups

#1069 feat: `Processing`/`Processed` flag on POS documents.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/base/util/ConvertUtil.java
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/pos/util/OrderConverUtil.java
  src/main/java/org/spin/pos/util/PaymentConvertUtil.java
  src/main/proto/point_of_sales.proto
Labels: enhancement, (POS) Point Of Sales, (FRM) Form

#1070 feat: Apply Order Discount by Schema Discount.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/pos/service/POSLogic.java
  src/main/java/org/spin/pos/util/ColumnsAdded.java
  src/main/proto/point_of_sales.proto
Labels: enhancement, (POS) Point Of Sales

#1071 fix: Display definition list only field.
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java
Labels: bug, (UX) User Experience

#1072 fix: Display Definition update business partner.
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java
Labels: bug, (ULP) UI Lookups, (UX) User Experience

#1073 fix: POS Partial order delivery.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/pos/service/POSLogic.java
  src/main/java/org/spin/pos/service/order/ShipmentUtil.java
  src/main/proto/point_of_sales.proto
Labels: bug, (POS) Point Of Sales, (UX) User Experience

#1074 fix: POS Product Price list with zero price and is sold.
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
Labels: bug, (POS) Point Of Sales

#1076 feat: Run process before search in a smart browse
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: enhancement, (SB) Smart Browser

#1078 feat: Smart Browser with `is_search_process` flag.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java
  src/main/proto/dictionary.proto
Labels: enhancement, (PRC) Processes, (SB) Smart Browser

#1079 fix: Display definition reference with insert/info record.
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java
Labels: bug, (WIN) Windows

#1081 configure Discount Schema
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
Labels: bug, (FRM) Form

#1080 Feature/validate operator browse search process
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: bug, (FRM) Form

#1082 Add Access Filter to businessPartner Search
  src/main/java/org/spin/grpc/service/field/business_partner/BusinessPartnerLogic.java
Labels: (SE) Security, (ULP) UI Lookups

#1083 feat: Change deprecated method `ValueManager.validateNull` to `StringManager.getValidString`.
  src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java
  src/main/java/org/spin/grpc/service/dictionary/ProcessConvertUtil.java
Labels: (CIO) Code Improvement or Optimization

#1084 fix: POS Validate cash before process order.
  src/main/java/org/spin/pos/service/order/OrderManagement.java
Labels: bug, (POS) Point Of Sales

#1085 feat: Print formtar with `Jasper Process ID`.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/ReportManagement.java
  src/main/proto/report_management.proto
Labels: enhancement, (REC) Records, (RPT) Reports, (WIN) Windows

#1086 When adding discount by amount in POS do not create InOutLine with charge
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
Labels: bug, (POS) Point Of Sales

#1087 feat: Report add flag `isForm` and `isStandardHeaderFooter`.
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/ReportManagement.java
  src/main/proto/report_management.proto
Labels: enhancement, (RPT) Reports

#1088 Bugfix Don't show display definition if role does not have access to window
  src/main/java/org/spin/base/util/AccessUtil.java
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionServiceLogic.java
Labels: bug, (SE) Security, (WIN) Windows

#1090 Create the CRUD endpoints for Gift Card in POS
  resources/adempiere-grpc-server.pb
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/proto/point_of_sales.proto
Labels: enhancement, (POS) Point Of Sales
