Repository solop-develop/adempiere-grpc-server, pull requests merged in 2025-08, with the labels that each got.

#1230 fix: Conversion rate with date on `Payment Allocation`.
  src/main/java/org/spin/grpc/service/form/payment_allocation/PaymentAllocationLogic.java
Labels: bug, (FRM) Form

#1229 Feat: Add Filter the Assignate
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementServiceLogic.java
  src/main/proto/issue_management.proto
Labels: enhancement, (UX) User Experience, (FRM) Form

#1231 feat: Add create conversion rate.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/base/util/GeneralLedgerConvertUtil.java
  src/main/java/org/spin/grpc/service/accounting/GeneralLedgerConvertUtil.java
  src/main/java/org/spin/grpc/service/accounting/GeneralLedgerService.java
  src/main/java/org/spin/grpc/service/accounting/GeneralLedgerServiceLogic.java
  src/main/java/org/spin/grpc/service/form/payment_allocation/PaymentAllocationConvertUtil.java
  src/main/java/org/spin/server/AllInOneServices.java
  src/main/proto/general_ledger.proto
Labels: enhancement, (ULP) UI Lookups

#1234 Calculate the Electronic Invoicing Summary Lines Before Prepare
  src/main/java/com/solop/sp013/core/model/validator/ElectronicInvoicing.java
Labels: enhancement

#1235 Separate Honorary Invoice Line in Electronic Summary
  src/main/java/com/solop/sp013/core/model/validator/ElectronicInvoicing.java
  src/main/java/com/solop/sp013/core/util/ElectronicInvoicingSummaryGrouping.java
Labels: enhancement

#1236 Remove adempiere-solop patch
  build.gradle
  gradle.properties
  src/main/java/org/spin/grpc/service/accounting/GeneralLedgerServiceLogic.java
  src/main/java/org/spin/grpc/service/form/payment_allocation/PaymentAllocationLogic.java
Labels: enhancement

#1239 feat: List conversion types on negotiated rate.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/accounting/GeneralLedgerServiceLogic.java
  src/main/proto/general_ledger.proto
Labels: enhancement, (ULP) UI Lookups

#1240 fix: CI GitHub actions with gradle 9.
  .settings/org.eclipse.jdt.core.prefs
  README.es.md
  README.md
  build.gradle
  docker/start.sh
Labels: bug, (CI/CD) Continuous Integration/Continous Delivery

#1241 fix: Validate role preference level to change.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/PreferenceManagement.java
  src/main/java/org/spin/grpc/service/Security.java
  src/main/proto/security.proto
Labels: bug, (SE) Security, (UX) User Experience

#1242 feat: Save multiple preferences.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/PreferenceManagement.java
  src/main/proto/preference_management.proto
Labels: enhancement, (UX) User Experience

#1243 fix: Pre-Release no replace latest and alpine tag.
  .github/workflows/ci.yml
  .github/workflows/publish.yml
Labels: bug, (CI/CD) Continuous Integration/Continous Delivery, (SE) Security, (CIO) Code Improvement or Optimization

#1247 feat: POS Is Direct Print.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/grpc/service/ReportManagement.java
  src/main/java/org/spin/pos/service/cash/CashServiceLogic.java
  src/main/java/org/spin/pos/service/pos/AccessManagement.java
  src/main/java/org/spin/pos/service/pos/POSConvertUtil.java
  src/main/proto/point_of_sales.proto
Labels: enhancement, (POS) Point Of Sales, (RPT) Reports

#1248 feat: Add print ticket with multiple files.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/grpc/service/PreferenceManagement.java
  src/main/java/org/spin/pos/service/order/OrderUtil.java
  src/main/proto/point_of_sales.proto
Labels: enhancement, (RPT) Reports

#1249 feat: Print Ticket multiple files.
  build.gradle
  src/main/java/org/spin/dictionary/util/ReportUtil.java
  src/main/java/org/spin/grpc/service/PaymentPrintExport.java
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/grpc/service/ReportManagement.java
Labels: enhancement, (POS) Point Of Sales, (RPT) Reports

#1251 Implement Batch Closing process and Status Services
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/pos/service/POSLogic.java
  src/main/java/org/spin/pos/service/cash/CashServiceLogic.java
  src/main/proto/point_of_sales.proto
Labels: enhancement, (POS) Point Of Sales

#1253 fix: Save multiple preferences.
  src/main/java/org/spin/grpc/service/PreferenceManagement.java
Labels: bug, (UX) User Experience

#1259 fix: Delete unused classes.
  src/main/java/org/spin/authentication/BearerToken.java
  src/main/java/org/spin/authentication/Constants.java
Labels: bug, (CIO) Code Improvement or Optimization

#1260 feat: Print Preview Cash Closing.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/pos/service/cash/CashServiceLogic.java
  src/main/proto/point_of_sales.proto
Labels: enhancement, (POS) Point Of Sales, (RPT) Reports

#1261 fix: POS no delete online payment with approval status.
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
Labels: bug, (POS) Point Of Sales

#1262 Print Online Cash Closing Voucher
  resources/adempiere-grpc-server.dsc
  src/main/java/com/solop/sp015/transact/processor/TransActCard.java
  src/main/java/org/compiere/interfaces/PaymentProcessorStatus.java
  src/main/java/org/compiere/model/MPayment.java
  src/main/java/org/solop/process/PrintVoucher.java
  src/main/java/org/solop/process/PrintVoucherAbstract.java
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/pos/service/cash/CashServiceLogic.java
  src/main/proto/point_of_sales.proto
Labels: enhancement, (POS) Point Of Sales

#1263 Fix print Online closing endpoint
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/pos/service/cash/CashServiceLogic.java
  src/main/proto/point_of_sales.proto
Labels: bug, (POS) Point Of Sales

#1267 Do not copy C_POS_ID in withdrawal from cash closing
  src/patches/org/spin/util/CashManagementUtil.java
Labels: bug, (POS) Point Of Sales

#1268 Do not split Online Closing Voucher
  src/patches/com/solop/sp015/transact/processor/TransActCard.java
Labels: bug, (POS) Point Of Sales

#1270 fix: Total tax amt.
  src/main/java/org/spin/pos/util/OrderConverUtil.java
Labels: bug, (POS) Point Of Sales

#1271 feat: List conversion rates by conversion type.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionality.java
  src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionalityConvert.java
  src/main/java/org/spin/grpc/service/core_functionality/CoreFunctionalityServiceLogic.java
  src/main/proto/core_functionality.proto
Labels: enhancement, (POS) Point Of Sales

#1273 fix: POS converterd display price.
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/pos/service/product/ProductConvertUtil.java
  src/main/java/org/spin/pos/service/product/ProductServiceLogic.java
Labels: bug, (POS) Point Of Sales

#1275 fix: Payment with other currency rounding amount.
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
  src/main/java/org/spin/pos/service/cash/CollectingManagement.java
Labels: bug, (POS) Point Of Sales
