Repository solop-develop/adempiere-grpc-server, pull requests merged in 2025-05, with the labels that each got.

#1125 feat: Update solop_libs to `clean-0.1.8`.
  gradle.properties
  src/main/java/org/spin/pos/service/order/OrderManagement.java
Labels: enhancement, (ULB) Update Library

#1126 Update solop_libs to clean-0.1.9
  gradle.properties
Labels: enhancement, (ULB) Update Library

#1129 fix: Browser Field sequence.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/dictionary/BrowseConverUtil.java
  src/main/java/org/spin/grpc/service/dictionary/WindowConvertUtil.java
  src/main/proto/dictionary.proto
Labels: bug, (SB) Smart Browser, (ULP) UI Lookups

#1130 Update Solop_libs to clean-0.2.0
  gradle.properties
Labels: enhancement, (ULB) Update Library

#1131 fix: SQL Browser changes.
  src/main/java/org/spin/base/db/OrderByUtil.java
  src/main/java/org/spin/base/db/QueryUtil.java
  src/main/java/org/spin/base/util/ReferenceUtil.java
  src/main/java/org/spin/grpc/service/Dashboarding.java
Labels: (SB) Smart Browser, (CIO) Code Improvement or Optimization

#1132 Filter available Sellers by SearchValue
  src/main/java/org/spin/grpc/service/PointOfSalesForm.java
Labels: bug, (POS) Point Of Sales, (UX) User Experience

#1133 Fix: Warehouse Location ID display column
  src/main/java/org/spin/base/util/ReferenceUtil.java
Labels: bug, (REC) Records, (ULP) UI Lookups

#1134 feat: Add recent item to `Browse`, `Window`, `Report` and `Process`.
  src/main/java/org/spin/grpc/service/BusinessData.java
  src/main/java/org/spin/grpc/service/ReportManagement.java
  src/main/java/org/spin/grpc/service/UserInterface.java
Labels: enhancement, dashboard, (PRC) Processes, (RPT) Reports, (SB) Smart Browser, (WIN) Windows

#1135 fix: Set selections if not empty.
  src/main/java/org/spin/grpc/service/BusinessData.java
Labels: bug, (PRC) Processes, (REC) Records

#1136 fix: Smart Browse with same System Element and column alias.
  src/main/java/org/spin/base/db/QueryUtil.java
  src/main/java/org/spin/base/util/ReferenceInfo.java
  src/main/java/org/spin/base/util/ReferenceUtil.java
Labels: bug, (REC) Records, (SB) Smart Browser

#1137 fix: Accounting Voew by record on table not is document.
  src/main/java/org/spin/grpc/logic/GeneralLedgerServiceLogic.java
  src/main/java/org/spin/grpc/service/GeneralLedger.java
Labels: bug, (WIN) Windows, (FRM) Form

#1138 fix: Load report views only active.
  src/main/java/org/spin/grpc/service/ReportManagement.java
Labels: bug, (RPT) Reports

#1140 feat: Add selection column.
  src/main/java/org/spin/grpc/service/dictionary/Dictionary.java
  src/main/java/org/spin/grpc/service/dictionary/DictionaryServiceLogic.java
  src/main/proto/dictionary.proto
Labels: enhancement

#1141 feat: Update solop-libs to `clean-0.3.4`.
  gradle.properties
Labels: enhancement, (ULB) Update Library

#1142 fix: Overwrite selection fields attributes.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/dictionary/DictionaryServiceLogic.java
Labels: bug, (RPT) Reports, (WIN) Windows

#1147 fix: Accouting on `Payment Allocation` form.
  gradle.properties
  src/main/java/org/spin/grpc/service/form/PaymentAllocation.java
Labels: bug, (FRM) Form
