Repository solop-develop/adempiere-grpc-server, pull requests merged in 2025-09, with the labels that each got.

#1283 Processor Batch Schedule Add Validations
  src/patches/org/adempiere/core/domains/models/I_C_PaymentProcessorSchedule.java
  src/patches/org/adempiere/core/domains/models/X_C_PaymentProcessorSchedule.java
  src/patches/org/compiere/model/MPaymentProcessorBatch.java
  src/patches/org/compiere/model/MPaymentProcessorSchedule.java
  src/patches/org/solop/process/GenerateARInvoiceFromBatch.java
Labels: bug

#1287 feat: Update gradlew scripts.
  gradlew
  gradlew.bat
Labels: enhancement, (CI/CD) Continuous Integration/Continous Delivery, (ULB) Update Library, (CIO) Code Improvement or Optimization

#1288 feat: Launch with `IntelliJ IDEA`.
  .idea/adempiere-grpc-server.iml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: enhancement, (CIO) Code Improvement or Optimization

#1289 feat: Add forms to recent items.
  src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchLogic.java
  src/main/java/org/spin/grpc/service/form/bank_statement_match/BankStatementMatchService.java
  src/main/java/org/spin/grpc/service/form/import_file_loader/ImportFileLoaderLogic.java
  src/main/java/org/spin/grpc/service/form/import_file_loader/ImportFileLoaderService.java
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementLogic.java
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementService.java
  src/main/java/org/spin/grpc/service/form/match_po_receipt_invoice/MatchPOReceiptInvoiceService.java
  src/main/java/org/spin/grpc/service/form/out_bound_order/OutBoundOrderLogic.java
  src/main/java/org/spin/grpc/service/form/payment_allocation/PaymentAllocationLogic.java
  src/main/java/org/spin/grpc/service/form/payment_allocation/PaymentAllocationService.java
  src/main/java/org/spin/grpc/service/form/payroll_action_notice/PayrollActionNoticeService.java
  src/main/java/org/spin/grpc/service/form/task_management/TaskManagementService.java
  src/main/java/org/spin/grpc/service/form/task_management/TaskManagemetLogic.java
  src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillableLogic.java
  src/main/java/org/spin/grpc/service/form/trial_balance_drillable/TrialBalanceDrillableService.java
  src/main/java/org/spin/server/AllInOneServices.java
Labels: enhancement, (FRM) Form

#1290 fix: Docker readme.
  README.es.md
  README.md
Labels: bug, documentation, (TRL) Translation

#1291 fix: Advanced query with Date infinite loop.
  src/main/java/org/spin/base/db/WhereClauseUtil.java
Labels: bug, (REC) Records, (SE) Security, (WIN) Windows

#1294 fix: Browser process all selection without Process Instance ID.
  src/main/java/org/spin/grpc/service/BusinessData.java
  src/main/java/org/spin/grpc/service/UserInterface.java
  src/main/java/org/spin/grpc/service/ui/BrowserLogic.java
Labels: bug, (PRC) Processes, (REC) Records, (SB) Smart Browser

#1297 Add Qty Consigned
  src/patches/org/solop/sp016/process/ConsolidateConsignmentSalesForInvoice.java
Labels: bug

#1299 fea: Display Definition add `IsCustom`.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/display_definition/DisplayDefinitionConvertUtil.java
  src/main/proto/display_definition.proto
Labels: enhancement, (WIN) Windows

#1320 feat: Add `Payment Method Allocation` discount rate.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/pos/service/cash/CollectingManagement.java
  src/main/java/org/spin/pos/service/order/OrderServiceLogic.java
  src/main/java/org/spin/pos/service/pos/POS.java
  src/main/proto/point_of_sales.proto
Labels: enhancement, (POS) Point Of Sales

#1321 fix: Request Status end point.
  resources/adempiere-grpc-server.dsc
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementLogic.java
  src/main/java/org/spin/grpc/service/form/issue_management/IssueManagementService.java
  src/main/proto/issue_management.proto
Labels: bug
